[package]
name = "scanprinter-beta"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.14.0"
polars = { version = "0.37.0", features = ["lazy"] }
tokio = "1.48.0"
polars-io = "0.37.0"
polars-core = "0.37.0"
